---
title: "analsis"
author: "by Socken"
date: "30-07-2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
library(knitr)
library(tidyverse)
use_python("/home/gabriel/anaconda3/bin/python")
```

#Carga de Datos


```{python}
import pandas as pd
datos = pd.read_csv("covid_19_clean_complete.csv")
datos.head(10)
```

```{r}
pd <- import("pandas")
datos<- pd$read_csv("covid_19_clean_complete.csv")
datos %>% head(10) %>% kable()
```

```
## Estructura de los datos
```{r}
str(datos)
colnames(datos)
```



```{r}
colnames(datos) = c("Provincia_Estado",
                    "Pais_Region",
                    "Latitud", # N+ o S-
                    "Longitud", # E+ o W-
                    "Fecha",
                    "Casos_Confirmados",
                    "Casos_Muertos",
                    "Casos_Recuperados",
                    "Activos",
                    "WHO Region"
                    )
datos %>% head() %>% kable() # %>% kable_styling()
```
* Cualitativas = factor as.factor
* Ordinales = ordered
* Cuantitativos = as.numeric

```{r}
str(datos)
```




