---
title: "R Notebook"
output: html_notebook
---

```{r}
install.packages("forecast")
library(forecast)
covid19=read.csv("covid_19_clean_complete.csv")
covid19$Date %<>% ymd()


covid19.España = covid19[covid19$Country.Region=="Spain",]

infectados.por.dia = aggregate(covid19.España$Confirmed ~ covid19.España$Date,FUN=sum)
fallecidos.por.dia = aggregate(covid19.España$Deaths ~ covid19.España$Date,FUN=sum)
recuperados.por.dia = aggregate(covid19.España$Recovered ~ covid19.España$Date,FUN=sum)

tabla.España = data.frame(unique(covid19.España$Date),infectados.por.dia[,2],
                          fallecidos.por.dia[,2],recuperados.por.dia[,2])
names(tabla.España) = c("Fecha", "Infectados","Fallecidos", "Recuperados")

infectados = ts(tabla.España$Infectados,frequency = 7,start=c(1,3))
infectados


plot.ts(infectados)
```

```{r}
componentes<-decompose(infectados, type="additive")
componentes$seasonal
```
```{r}
autoplot(componentes)
```
```{r}
infectados.ajustados = infectados-componentes$seasonal
plot(infectados.ajustados)
autoplot(infectados.ajustados)
```

```{r}
(predicción.infectados=HoltWinters(infectados.ajustados,gamma=FALSE))
```
```{r}
predicción.infectados$SSE
sqrt(predicción.infectados$SSE)
plot(predicción.infectados)
```
```{r}
(predicción.infectados.semana = forecast:::forecast.HoltWinters(predicción.infectados, h=7))
```

```{r}
forecast:::plot.forecast(predicción.infectados.semana)
```
```{r}
acf(predicción.infectados.semana$residuals[3:75], lag.max=7)
```
```{r}
Box.test(predicción.infectados.semana$residuals,lag=7,type="Ljung-Box")
```
```{r}
shapiro.test(predicción.infectados.semana$residuals)
```

